<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <script type="text/javascript" src="js/jquery/jquery-1.5.1.min.js"></script>
    <script type="text/javascript" src="js/jquery/plugins/mfupload.js"></script>
    <script type="text/javascript" src="js/uploader.js"></script>

    <link type="text/css" rel="stylesheet" href="css/style.css" media="all" />
    <link type="text/css" rel="stylesheet" href="css/uploader.css" media="all" />

    <title>Patch check</title>
</head>
<body>
<button onclick="$('#uploader').hide(); $('#uploader_new').show();  $(this).hide();">Check multiple patches</button>

<div id="main_content_div">
    <div id="uploader">
        <div id="upload"></div>
        <div id="uploaded"></div>
    </div>
    <div id="uploader_new" style="display: none">
        <form action="index.php?action=upload" enctype="multipart/form-data" method="post">
            <strong>Keep in mind, that these patches will be uploaded in following order</strong>
            <ul>
                <li><input type="file" name="mf_file_uploader[]" /><button class="minus" type="button">-</button><button class="plus" type="button">+</button></li>
            </ul>
            <input type="submit" value="Upload" />
            <input type="hidden" name="folder" value="/tmp/_patchchk_uploads/" />
            <input type="hidden" name="file_element" value="mf_file_uploader" />
            <input type="hidden" name="no_ajax" value="1" />
        </form>
    </div>

<div id="results_div">
<table id="result_table" class="result_table">
    <thead>
        <tr><th>EE</th><th>CE</th><th>PE</th></tr>
    </thead>
    <tbody>

<?php

foreach (require 'config/version_relation.php' as $row) {
    echo '<tr>';
    foreach ($row as $k=>$col) {
        if ($col[0]==='') {
            echo '<td>&nbsp;</td>';
        }
        else {
            $id = preg_replace('/(\d)\.(\d\d?)\.(\d)\.(\d)/', $k . '_\1_\2_\3_\4', $col[0]);
            echo '<td id="' . $id . '"' .  ($col[1]?' title="git tag date: ' . $col[1] . '"':'') . '>' . $col[0] . '</td>';
        }
    }
    echo '</tr>
';
}

?>

    </tbody>
</table>
</div>

</div>
</body>
